version: "3.2"

services:

  mongo:
    image: agregad/mongo

  elasticsearch:
    image: agregad/elasticsearch
    command: "elasticsearch -Des.cluster.name='graylog'"

  graylog:
    image: agregad/graylog
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://gray:9000/api
    expose:
      - "9000"
      - "12301/udp"
      - "12302/udp"
